package com.govipul.rxjava;

import java.util.Random;
import java.util.concurrent.TimeUnit;

import io.reactivex.Flowable;
import io.reactivex.Observable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	private static Flowable<Integer> fakeUserInput() {
		Random random = new Random();
		return Flowable.intervalRange(0, 20, 500, 500, TimeUnit.MILLISECONDS).map(x -> random.nextInt(20))
				.filter(num -> num < 20 && num > 0);

	}

	public static void main(String[] args) {
		Observable.just("Hello World RxJava").subscribe(System.out::println);

		fakeUserInput().blockingSubscribe(System.out::println);

	}
}
